### ISSUE TITLE
how to test the scannet model.ckpt?

### ISSUE THREAD

**Issue by kkyan1995** [mathieuorhan/pointnet2_semantic#2]
I want to test the model for scannet , but it is wrong when i run predict.py ,is it just for semantic testing ?

**Comment by luoxiaoliaolan** [comment]
@kkyan1995 
Maybe you can try to train the scannet dataset with pointnet++ (https://github.com/charlesq34/pointnet2/tree/master/scannet)

**Comment by kkyan1995** [comment]
thank you
