### ISSUE TITLE
Problem about the testing task on ScanNet

### ISSUE THREAD

**Issue by RicheyHuang** [mathieuorhan/pointnet2_semantic#3]
Hello, thanks for offering this handy tool and it really helps a lot. I found some problems when I used the trained model to predict the segmentation results on ScanNet. I saw some codes were added to process z-feature, but it was just for Semantic3D dataset. When I run predict.py to handle the testing task on ScanNet, some errors just occured, showing that z_feature was an unexpected keyword argument. Can you please give me some advices to solve this?

**Comment by luoxiaoliaolan** [comment]
@RicheyHuang 
Maybe you can try to train the scannet dataset with pointnet++ (https://github.com/charlesq34/pointnet2/tree/master/scannet)

**Comment by RicheyHuang** [comment]
@luoxiaoliaolan Thanks for your advice. I finally wrote some codes for the testing and evaluation tasks on ScanNet, referring to the codes of pointnet++, and it worked perfectly~ :)

**Comment by luoxiaoliaolan** [comment]
@RicheyHuang  那真是很棒啊！我关注研究这个点云深度学习有一段时间了，我处理的都是激光点云数据，没有像ScanNet那样的RGBD数据。希望在这个项目上与你保持联系！！可以加个好友

**Comment by RicheyHuang** [comment]
@luoxiaoliaolan 这是我的邮箱: richeyhuang22@gmail.com, 大家一起学习探讨~

**Comment by longmalongma** [comment]
> @luoxiaoliaolan Thanks for your advice. I finally wrote some codes for the testing and evaluation tasks on ScanNet, referring to the codes of pointnet++, and it worked perfectly~ :)

Hello,you are good.I can not write some codes for the testing and evaluation tasks on ScanNet about pointnet++,can you send me those codes to email:1442342449@qq.com.thanks you very much,looking forward your reply.

**Comment by longmalongma** [comment]
> @luoxiaoliaolan 这是我的邮箱: [richeyhuang22@gmail.com](mailto:richeyhuang22@gmail.com), 大家一起学习探讨~


Hello,you  are good.I can not write some codes for the testing and evaluation  tasks on ScanNet about pointnet++,can you send me those codes to email:1442342449@qq.com.thanks you very much,looking forward your reply.
--

**Comment by Naor92** [comment]
> Hello, thanks for offering this handy tool and it really helps a lot. I found some problems when I used the trained model to predict the segmentation results on ScanNet. I saw some codes were added to process z-feature, but it was just for Semantic3D dataset. When I run predict.py to handle the testing task on ScanNet, some errors just occured, showing that z_feature was an unexpected keyword argument. Can you please give me some advices to solve this?

Hi @RicheyHuang - I am running into the same issue here. Can you share what you did to fix this?
